[[libsurfgen]]
arch = "x86_64"
git-tree-sha1 = "271244612371bc9c4d0f6892722681404dd675b4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[libsurfgen.download]]
    sha256 = "b03577bd6ec0ec9742770809cc0ca2c1b7984bab0d7135d8abeb0b858500d10f"
    url = "https://github.com/NQCD/libsurfgen_jll.jl/releases/download/libsurfgen-v0.1.0+0/libsurfgen.v0.1.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[libsurfgen]]
arch = "x86_64"
git-tree-sha1 = "0e628367aafc3998731d02f743afaf075d8011f5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[libsurfgen.download]]
    sha256 = "0a61112737b439d1dac5c1e88d57f0ce8b5aad6bc58f28d4ec6f822b881d5375"
    url = "https://github.com/NQCD/libsurfgen_jll.jl/releases/download/libsurfgen-v0.1.0+0/libsurfgen.v0.1.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[libsurfgen]]
arch = "x86_64"
git-tree-sha1 = "aaeb40ffc70cd916c986f25a2293b0746e368124"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[libsurfgen.download]]
    sha256 = "42800fc2319d02ec49ce290a5e97234fc93b98d055c7d8800c1a3a93d5246f1e"
    url = "https://github.com/NQCD/libsurfgen_jll.jl/releases/download/libsurfgen-v0.1.0+0/libsurfgen.v0.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
